### ISSUE TITLE
Office 2016 Issue - Acting As If ALT Is Pressed

### ISSUE THREAD

**Issue by joshsevers** [T800G/OfficeScroll#12]
Works fine, but in Excel 2016 (Windows 10, ver 1903, 64-bit), scrolling one tick will display the letters above each ribbon as if I had it the ALT key to begin a shortcut sequence. Scrolling one more tick will remove them, one more brings them back, etc.

It's as if each scroll tick is somehow triggering a press of ALT+SHIFT, which is a shortcut for switching language keyboards if it's enabled. This is likely causing the issues others mentioned.

Tried both shift keys, same results, tried with Scroll Lock enabled, same results.

**Comment by Koolstr** [comment]
I can confirm having the same issue. On each scroll tick, the keyboard language gets swapped along with the ALT key activating/deactivating selection of the ribbon buttons. 
This utility works great otherwise, but this particular bug is troubling enough to be a dealbreaker for me. I'll be sticking to custom AutoHotKey scripts in the meantime.

**Comment by T800G** [comment]
Fixed Ribbon tooltips problem.
This addin sends additional Alt key strokes to hide ribbon tooltips. If you use multiple system input languages/keyboards, set the input language switch key to "Not assigned" (Control panel -> Regional settings) and enable language bar in taskbar to switch languages through right-click on it..
